steps:
# Step 1: Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gke-demo:$COMMIT_SHA', '.']

# Step 2: Push the image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gke-demo:$COMMIT_SHA']

# Step 3: Set up kubectl credentials
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials gke-cluster \
      --zone us-central1 \
      --project $PROJECT_ID

# Step 4: Apply Kubernetes manifests
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s-manifests/']
  env:
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'

images:
- 'gcr.io/$PROJECT_ID/gke-demo:$COMMIT_SHA'
